# This is a basic workflow to help you get started with Actions

name: merge

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to bump to'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: javascript ./.github/worldflows/merge.js
      
