# This is a basic workflow to help you get started with Actions

name: merge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: |
          printf "Hello\nWorld\n" > hw.txt
      - name: Create file
        run: |
          echo First > other.txt
          echo Second >> other.txt
          echo Third >> other.txt
      - name: Show file content
        run: |
          pwd
          ls -la
          cat hw.txt
          cat other.txt
