# This is a basic workflow to help you get started with Actions

name: merge

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: |
        mkdir -p myNewFolder && cp -R dist myNewFolder
        ls myNewFolder
      
